AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template creates an EC2 instance based on the region and selection of an
  AMI ID. It also will create a Security Group.
Parameters:
  MySubnet:
    Description: My subnet from my VPC
    Type: String
    Default: subnet-YYYYYYYY
  MySG:
    Description: My Security Group from my VPC
    Type: String
    Default: SG-YYYYYYYY
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Mappings:
  AWSInstanceType2Arch:
    t3.micro:
      Arch: HVM64
  AWSInstanceType2NATArch:
    t3.micro:
      Arch: NATHVM64      
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0beafb294c86717a8
      HVMG2: ami-02354e95b39ca8dec
    us-west-2:
      HVM64: ami-041fcb43d4730cf32
      HVMG2: ami-0873b46c45c11058d
    us-west-1:
      HVM64: ami-0a1ef8665fe122a96
      HVMG2: ami-05655c267c89566dd
    eu-west-1:
      HVM64: ami-06cd7f9c4486344a5
      HVMG2: ami-07d9160fa81ccffb5
    eu-west-2:
      HVM64: ami-01ac84be28584498d
      HVMG2: ami-0a13d44dccf1f5cf6
    eu-west-3:
      HVM64: ami-0a682c61cac068f2f
      HVMG2: ami-093fa4c538885becf 
    eu-central-1:
      HVM64: ami-05d403b512bf100eb
      HVMG2: ami-0c115dbd34c69a004
    eu-north-1:
      HVM64: ami-0dd62557e4298551a
      HVMG2: ami-039609244d2810a6b
    ap-northeast-1:
      HVM64: ami-0d1e3062992b86514
      HVMG2: ami-0cc75a8978fbbc969
    ap-northeast-2:
      HVM64: ami-07a28b8671656c8c1
      HVMG2: ami-0bd7691bf6470fe9c
    ap-northeast-3:
      HVM64: ami-0e740663443574970
      HVMG2: ami-043bb1ed348aaf857
    ap-southeast-1:
      HVM64: ami-00c3854c1706a382f 
      HVMG2: ami-0cd31be676780afa7
    ap-southeast-2:
      HVM64: ami-09ba19d0563c3d553
      HVMG2: ami-0ded330691a314693
    ap-south-1:
      HVM64: ami-0571d68822206714c
      HVMG2: ami-0ebc1ac48dfd14136
    us-east-2:
      HVM64: ami-0f4665edc97a93bea
      HVMG2: ami-07c8bc5c1ce9598c3
    ca-central-1:
      HVM64: ami-0a7c38a2574890e5c
      HVMG2: ami-013d1df4bcea6ba95
    sa-east-1:
      HVM64: ami-0cd294bc0ed0be0e4
      HVMG2: ami-018ccfb6b4745882a
    cn-north-1:
      HVM64: ami-053617c9d818c1189
      HVMG2: NOT_SUPPORTED
    cn-northwest-1:
      HVM64: ami-0f7937761741dc640
      HVMG2: NOT_SUPPORTED
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref MySubnet
      SecurityGroupIds:
        - !Ref MySG
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - PublicIp
